project:
  type: website
  render:
    - index.qmd
    - Emissionen.qmd
    - Immissionen.qmd
    - Exposition.qmd
    - Gesundheitsfolgen.qmd
    - about.qmd
  # pre-render: "read_plots.R"

website:
  title: "Luftqualität im Kanton Zürich"
  navbar:
    background: light
    search: true
    pinned: true
    # logo: "logo/logo.png"
    logo-href: "https://www.zh.ch/de/baudirektion/amt-fuer-abfall-wasser-energie-luft.html"
    left:
      - href: index.qmd
        text: Allgemeines
      - href: Emissionen.qmd
        text: Emissionen
      - href: Immissionen.qmd
        text: Immissionen
      - href: Exposition.qmd
        text: Exposition
      - href: Gesundheitsfolgen.qmd
        text: Gesundheitsfolgen
    right: 
      - about.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc_float:
      collapsed: false

lightbox: true
fig-cap-location: margin
reference-location: margin
callout-appearance: default

knitr:
  opts_chunk: 
    collapse: true
    echo: false
    warning: false
    message: false
    fig.width: 9
    fig.asp: 0.5


