---
title: "Trends"
lightbox: true
---


<!-- Hier werden ausgewählte Luftqualitäts-Messdaten aus dem interkantonalen Messnetz zur  [Luftqualitätsüberwachung der Ostschweizer Kantone und des Fürstentums Liechtenstein Ostluft](https://www.ostluft.ch/) sowie aus dem [nationalen Beobachtungsnetz für Luftfremdstoffe NABEL](https://www.bafu.admin.ch/bafu/de/home/themen/luft/zustand/daten/nationales-beobachtungsnetz-fuer-luftfremdstoffe--nabel-.html) im Kanton Zürich dargestellt. Belastungskarten mit flächendeckenden Informationen zur Luftqualität finden sich im [GIS-Browser des Kantons Zürich](https://geo.zh.ch/maps). In Darstellungen der Langzeitverläufe der Schadstoffkonzentrationen (Immissionsverläufe) werden die aktuellen Grenzwerte über den Gesamtzeitraum konstant dargestellt, auch wenn sie erst ab einem bestimmten Zeitpunkt in der [Luftreinhalteverordnung des Bundes](https://www.fedlex.admin.ch/eli/cc/1986/208_208_208/de) eingeführt oder angepasst wurden. Das Gleiche gilt für die [Richtwerte der Weltgesundheitsorganisation WHO](https://www.who.int/publications/i/item/9789240034228). -->
<!-- <!-- bzw. dem [GIS-Browser des Bundes](https://map.geo.admin.ch/). --> -->


```{r}
source("read_plots.R")
plots <- readRDS("plots_trends.rds")
```


### Relative Entwicklung Emissionen / Immissionen

::: {.panel-tabset}

#### einfach

```{r}
#| label: fig-trends-rel
get_plot(plots, "pollutant == 'timeseries' & source == 'relative'")
```

#### detailliert

```{r}
#| label: fig-trends-rel-detail
get_plot(plots, "pollutant == 'timeseries_detailed' & source == 'relative'")
```


