require(fs)
require(readr)
require(archive)
require(httr2)
require(httr)
require(tibble)
require(tidyr)
require(dplyr)
require(stringr)
require(purrr)
require(rlang)
require(lubridate)
require(zoo)
require(sf)
require(stars)
require(ows4R)
require(ggplot2)
require(ggh4x)
require(scales)
require(lemon)
require(openair)
require(shades)
require(wesanderson)
require(rOstluft) # https://github.com/Ostluft/rOstluft
require(rOstluft.plot) # https://github.com/Ostluft/rOstluft.plot
